#%RAML 1.0 NamedExample
value:

  - 
    firstName: Andre
    lastName: Silva
    address: 123 Parkway Forest Dr
    postal: M2J0G1
    country: Canada
    miles: 12
    type: Type
  - 
    firstName: Andre 2
    lastName: Silva 2
    address: 1232 Parkway Forest Dr
    postal: M2J0G2
    country: Canada
    miles: 56
    type: Type 2
