#%RAML 1.0 NamedExample
value:

    ID?: 1
    firstName: Andre
    lastName: Silva
    address: 123 Parkway Forest Dr
    postal: M2J0G1
    country: Canada
    miles: 12
    creationDate: 2019-06-10T13:15:41.090Z
    type: Type
